### ISSUE TITLE
instructions on data and running dsc?

### ISSUE THREAD

**Issue by stephens999** [mengyin/EBNM#1]
can you add the data you used? (Is it a counts matrix? If so then should be ok to add here).
And add brief instructions on how to run the dsc and produce plots?

**Comment by mengyin** [comment]
Thanks for the advice! 
Data file is uploaded to https://github.com/mengyin/EBNM/tree/master/data
DSC instructions: https://github.com/mengyin/EBNM/blob/master/dsc-poisthin-indep/README.md
R code to produce plots: https://github.com/mengyin/EBNM/blob/master/analysis/plots.R
Rmd showing how to produce plots: https://github.com/mengyin/EBNM/blob/master/analysis/simulation.Rmd
