### ISSUE TITLE
packages that need installing

### ISSUE THREAD

**Issue by stephens999** [mengyin/EBNM#3]
can you add a list of packages that need to be installed?

eg limma, DESeq2
others?

**Comment by mengyin** [comment]
No problem, I added them to the readme file:
https://github.com/mengyin/EBNM-moderated-t/blob/master/dsc-poisthin-indep/README.md

**Comment by stephens999** [comment]
This is awesome.
note:

- move the CRAN installations before the github ones.

- ashr is on CRAN. installing from there will also install dependencies like truncnorm which seems
to be required by vashr

- I needed foreach and pscl from CRAN before vash would install.
- I needed SQUAREM from CRAN before vicar would install. 
- I needed dplyr,shiny for dscr to run

Can you add ashr,SQUAREM, foreach, pscl,dplyr,shiny
to the cran list and move those installations before the github ones?

**Comment by mengyin** [comment]
> This is awesome.
> note:
> 
> * move the CRAN installations before the github ones.
> * ashr is on CRAN. installing from there will also install dependencies like truncnorm which seems
>   to be required by vashr
> * I needed foreach and pscl from CRAN before vash would install.
> * I needed SQUAREM from CRAN before vicar would install.
> * I needed dplyr,shiny for dscr to run
> 
> Can you add ashr,SQUAREM, foreach, pscl,dplyr,shiny
> to the cran list and move those installations before the github ones?

Thanks a lot for the suggestions! I fixed them in the readme file.
